// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApm355oimRLgnP2OenZVC0AvJc6VIWQVI',
    appId: '1:993486217751:web:f7fad91d9b946cba417252',
    messagingSenderId: '993486217751',
    projectId: 'my-park-74736',
    authDomain: 'my-park-74736.firebaseapp.com',
    storageBucket: 'my-park-74736.appspot.com',
    measurementId: 'G-81T7Z5LQZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIM0JcLJ3k4AAFnOYMgBBAb4-GvdEFqaM',
    appId: '1:993486217751:android:0a773faca4744af0417252',
    messagingSenderId: '993486217751',
    projectId: 'my-park-74736',
    storageBucket: 'my-park-74736.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH8JN6PM5takZf2NqTZ2H4vqDgECmWrVE',
    appId: '1:993486217751:ios:ee6015ec85cf3cfb417252',
    messagingSenderId: '993486217751',
    projectId: 'my-park-74736',
    storageBucket: 'my-park-74736.appspot.com',
    iosBundleId: 'com.hassansapplication.app',
  );
}
