// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC99KlYlpBhDUEBaoPdMxGnjBT2-iHDynI',
    appId: '1:286242714665:web:b54d2c7da87702bd129838',
    messagingSenderId: '286242714665',
    projectId: 'my-park-6b559',
    authDomain: 'my-park-6b559.firebaseapp.com',
    storageBucket: 'my-park-6b559.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlyoHu6Da6Jpr_65Y8mzSAkfJfqQi3pCE',
    appId: '1:286242714665:android:ddab6836ab63b412129838',
    messagingSenderId: '286242714665',
    projectId: 'my-park-6b559',
    storageBucket: 'my-park-6b559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_S-7MsKIDm3H0IihXzUZh7V25KbOmdzQ',
    appId: '1:286242714665:ios:f4de4e8af5bc6476129838',
    messagingSenderId: '286242714665',
    projectId: 'my-park-6b559',
    storageBucket: 'my-park-6b559.appspot.com',
    iosBundleId: 'com.hassansapplication.app',
  );
}
